name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
  release:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[release]')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - run: |
          VERSION=$(jq -r .version package.json)
          TAG="v$VERSION"
          if [ -n "$(git ls-remote --tags origin refs/tags/$TAG)" ]; then
            counter=1
            while [ -n "$(git ls-remote --tags origin refs/tags/${TAG}_${counter})" ]; do
              counter=$((counter + 1))
            done
            TAG="${TAG}_${counter}"
          fi
          echo "TAG_NAME=$TAG" >> $GITHUB_ENV

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ env.TAG_NAME }} --generate-notes
